<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Entity\Factory;

use RK\LandingPagesModule\Entity\Factory\Base\AbstractEntityFactory;

/**
 * Factory class used to create entities and receive entity repositories.
 */
class EntityFactory extends AbstractEntityFactory
{
    // feel free to customise the factory
}
