<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Helper;

use RK\LandingPagesModule\Helper\Base\AbstractSearchHelper;

/**
 * Search helper implementation class.
 */
class SearchHelper extends AbstractSearchHelper
{
    // feel free to extend the search helper here
}
