<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Form\Handler\Image;

use RK\LandingPagesModule\Form\Handler\Image\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the image object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
