<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Form\Type\Finder;

use RK\LandingPagesModule\Form\Type\Finder\Base\AbstractImageFinderType;

/**
 * Image finder form type implementation class.
 */
class ImageFinderType extends AbstractImageFinderType
{
    // feel free to extend the base form type class here
}
