<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Validator\Constraints;

use RK\LandingPagesModule\Validator\Constraints\Base\AbstractListEntry;

/**
 * List entry validation constraint.
 *
 * @Annotation
 */
class ListEntry extends AbstractListEntry
{
    // here you can customise the constraint
}
