<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Form\Handler\Page;

use RK\LandingPagesModule\Form\Handler\Page\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKLandingPagesModule_page_edit() function.
 * It aims on the page object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
