services:
    # Event subscribers and listeners
    rk_landingpages_module.entity_lifecycle_listener:
        class: RK\LandingPagesModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags: ['doctrine.event_subscriber']
    
    rk_landingpages_module.kernel_listener:
        class: RK\LandingPagesModule\Listener\KernelListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.installer_listener:
        class: RK\LandingPagesModule\Listener\InstallerListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.moduledispatch_listener:
        class: RK\LandingPagesModule\Listener\ModuleDispatchListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.mailer_listener:
        class: RK\LandingPagesModule\Listener\MailerListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.theme_listener:
        class: RK\LandingPagesModule\Listener\ThemeListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.userlogin_listener:
        class: RK\LandingPagesModule\Listener\UserLoginListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.userlogout_listener:
        class: RK\LandingPagesModule\Listener\UserLogoutListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.user_listener:
        class: RK\LandingPagesModule\Listener\UserListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.userregistration_listener:
        class: RK\LandingPagesModule\Listener\UserRegistrationListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.users_listener:
        class: RK\LandingPagesModule\Listener\UsersListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.group_listener:
        class: RK\LandingPagesModule\Listener\GroupListener
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.thirdparty_listener:
        class: RK\LandingPagesModule\Listener\ThirdPartyListener
        arguments:
            - "@filesystem"
            - "@request_stack"
        tags: ['kernel.event_subscriber']
    
    rk_landingpages_module.workflow_events_listener:
        class: RK\LandingPagesModule\Listener\WorkflowEventsListener
        arguments:
            - "@zikula_permissions_module.api.permission"
        tags: ['kernel.event_subscriber']
    
