services:
    # Helper services
    rk_landingpages_module.collection_filter_helper:
        class: RK\LandingPagesModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@=service('zikula_extensions_module.api.variable').get('RKLandingPagesModule', 'showOnlyOwnEntries', false)"
    
    rk_landingpages_module.controller_helper:
        class: RK\LandingPagesModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@rk_landingpages_module.entity_factory"
            - "@rk_landingpages_module.collection_filter_helper"
            - "@rk_landingpages_module.model_helper"
            - "@rk_landingpages_module.image_helper"
    
    rk_landingpages_module.entity_display_helper:
        class: RK\LandingPagesModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@rk_landingpages_module.listentries_helper"
    
    rk_landingpages_module.hook_helper:
        class: RK\LandingPagesModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    rk_landingpages_module.image_helper:
        class: RK\LandingPagesModule\Helper\ImageHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@zikula_extensions_module.api.variable"
    
    rk_landingpages_module.listentries_helper:
        class: RK\LandingPagesModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    rk_landingpages_module.model_helper:
        class: RK\LandingPagesModule\Helper\ModelHelper
        arguments:
            - "@rk_landingpages_module.entity_factory"
    
    rk_landingpages_module.search_helper:
        class: RK\LandingPagesModule\Helper\SearchHelper
        arguments:
            - "@translator.default"
            - "@zikula_permissions_module.api.permission"
            - "@session"
            - "@request_stack"
            - "@rk_landingpages_module.entity_factory"
            - "@rk_landingpages_module.controller_helper"
            - "@rk_landingpages_module.entity_display_helper"
        tags:
            - { name: zikula.searchable_module, bundleName: RKLandingPagesModule }
    
    rk_landingpages_module.upload_helper:
        class: RK\LandingPagesModule\Helper\UploadHelper
        arguments:
            - "@translator.default"
            - "@filesystem"
            - "@session"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').getAll('RKLandingPagesModule')"
            - "%datadir%"
    
    rk_landingpages_module.view_helper:
        class: RK\LandingPagesModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@rk_landingpages_module.controller_helper"
    
    rk_landingpages_module.workflow_helper:
        class: RK\LandingPagesModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_landingpages_module.entity_factory"
            - "@rk_landingpages_module.listentries_helper"
