services:
    # Custom validators
    rk_landingpages_module.validator.list_entry.validator:
        class: RK\LandingPagesModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@rk_landingpages_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: rk_landingpages_module.validator.list_entry.validator }
