<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule;

use RK\LandingPagesModule\Base\AbstractLandingPagesEvents;

/**
 * Events definition implementation class.
 */
class LandingPagesEvents extends AbstractLandingPagesEvents
{
    // feel free to extend the events definition here
}
