<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule;

use RK\LandingPagesModule\Base\AbstractRKLandingPagesModule;

/**
 * Module implementation class.
 */
class RKLandingPagesModule extends AbstractRKLandingPagesModule
{
    // custom enhancements can go here
}
