<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\LandingPagesModule\Entity\PageEntity;

/**
 * Event base class for filtering page processing.
 */
class AbstractFilterPageEvent extends Event
{
    /**
     * @var PageEntity Reference to treated entity instance.
     */
    protected $page;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterPageEvent constructor.
     *
     * @param PageEntity $page Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(PageEntity $page, $entityChangeSet = [])
    {
        $this->page = $page;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return PageEntity
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
