<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Listener;

use RK\LandingPagesModule\Listener\Base\AbstractKernelListener;

/**
 * Event handler implementation class for Symfony kernel events.
 */
class KernelListener extends AbstractKernelListener
{
    // feel free to enhance the parent methods
}
