<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Listener;

use RK\LandingPagesModule\Listener\Base\AbstractThemeListener;

/**
 * Event handler implementation class for theme-related events.
 */
class ThemeListener extends AbstractThemeListener
{
    // feel free to enhance the parent methods
}
