<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\DependencyInjection;

use RK\LandingPagesModule\DependencyInjection\Base\AbstractRKLandingPagesExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKLandingPagesExtension extends AbstractRKLandingPagesExtension
{
    // custom enhancements can go here
}
