<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Entity;

use RK\LandingPagesModule\Entity\Base\AbstractImageEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for image entities.
 * @ORM\Entity(repositoryClass="RK\LandingPagesModule\Entity\Repository\ImageRepository")
 * @ORM\Table(name="rk_landpa_image",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class ImageEntity extends BaseEntity
{
    // feel free to add your own methods here
}
