<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Form\Type\Field;

use RK\LandingPagesModule\Form\Type\Field\Base\AbstractUploadType;

/**
 * Upload field type implementation class.
 */
class UploadType extends AbstractUploadType
{
    // feel free to add your customisation here
}
