<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Event;

use RK\LandingPagesModule\Event\Base\AbstractFilterPageEvent;

/**
 * Event implementation class for filtering page processing.
 */
class FilterPageEvent extends AbstractFilterPageEvent
{
    // feel free to extend the event class here
}
