<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Form\Type;

use RK\LandingPagesModule\Form\Type\Base\AbstractImageType;

/**
 * Image editing form type implementation class.
 */
class ImageType extends AbstractImageType
{
    // feel free to extend the image editing form type class here
}
