<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\Entity\Factory\Base;

use RK\LandingPagesModule\Entity\PageEntity;
use RK\LandingPagesModule\Entity\ImageEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given page instance.
     *
     * @param PageEntity $entity The newly created entity instance
     *
     * @return PageEntity The updated entity instance
     */
    public function initPage(PageEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given image instance.
     *
     * @param ImageEntity $entity The newly created entity instance
     *
     * @return ImageEntity The updated entity instance
     */
    public function initImage(ImageEntity $entity)
    {

        return $entity;
    }

}
