<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.5 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\HookSubscriber;

use RK\LandingPagesModule\HookSubscriber\Base\AbstractPageFilterHooksSubscriber;

/**
 * Implementation class for filter hooks subscriber.
 */
class PageFilterHooksSubscriber extends AbstractPageFilterHooksSubscriber
{
    // feel free to add your own convenience methods here
}
