<?php
/**
 * LandingPages.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.2 (https://modulestudio.de).
 */

namespace RK\LandingPagesModule\HookSubscriber;

use RK\LandingPagesModule\HookSubscriber\Base\AbstractPageFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class PageFormAwareHookSubscriber extends AbstractPageFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
